/**
 * Complete form configuration structure generated by ReactFormBuilderService.
 * Represents the entire form definition including program, funding opportunity, and form steps.
 */
export interface ReactFormConfiguration {
	/** Configuration version */
	Version: string;
	/** Program configuration */
	Program?: ReactProgramConfiguration;
	/** Funding opportunity configuration */
	FundingOpportunity: ReactFundingOpportunityConfiguration;
	/** Form definition */
	Form: ReactForm;
	/** Optional table metadata keyed by entity logical name */
	TableMetadata?: Record<string, ReactTableMetadataEntry>;
}

/**
 * Program configuration.
 */
export interface ReactProgramConfiguration {
	/** Program record ID */
	Id: string;
}

/**
 * Funding opportunity configuration.
 */
export interface ReactFundingOpportunityConfiguration {
	/** Funding opportunity record ID */
	Id: string;
	/** Short name */
	Name: string;
	/** Full name */
	FullName: string;
	/** Funding opportunity settings */
	Settings: ReactFundingOpportunitySettings;
	/** Application table configuration for funding opportunity */
	ApplicationTable: ReactApplicationTableConfiguration;
}

/**
 * Funding opportunity settings.
 */
export interface ReactFundingOpportunitySettings {
	/** Whether identity verification is enabled */
	IdentityVerificationEnabled: boolean;
	/** Late submission allowed until date */
	LateSubmissionAllowedUntil?: string;
}

/**
 * Application table configuration.
 */
export interface ReactApplicationTableConfiguration {
	/** Application table record ID */
	Id: string;
	/** Application table name */
	Name: string;
	/** Dataverse table logical name */
	TableLogicalName: string;
	/** Description */
	Description?: string;
	/** Usage type */
	Usage?: number;
}

/**
 * Form definition.
 */
export interface ReactForm {
	/** Form record ID */
	Id: string;
	/** Form name */
	Name: string;
	/** Primary application table for this form */
	PrimaryApplicationTable: ReactApplicationTableConfiguration;
	/** Introduction text */
	Introduction?: string;
	/** Form settings */
	Settings: ReactFormSettings;
	/** Ordered list of form steps */
	Steps: ReactFormStep[];
	/** Table metadata for entities referenced in the form */
	TableMetadata?: Record<string, ReactTableMetadataEntry>;
}

/**
 * Form settings.
 */
export interface ReactFormSettings {
	/** Whether to include in application package */
	IncludeInApplicationPackage?: boolean;
	/** Application package types to include on */
	ApplicationPackageTypesToIncludeOn: (number | null)[];
	/** Whether form is required for applicant */
	RequireFormForApplicant: boolean;
	/** Estimated completion time */
	EstimatedCompletionTime?: string;
}

/**
 * Table metadata for a Dataverse entity.
 */
export interface ReactTableMetadataEntry {
	/** Entity logical name */
	EntityLogicalName: string;
	/** Entity schema name */
	EntitySchemaName?: string;
	/** Entity set name (collection name) */
	EntitySetName?: string;
	/** Entity display name */
	EntityDisplayName?: string;
	/** Entity description */
	EntityDescription?: string;
	/** Primary ID attribute */
	PrimaryIdAttribute?: string;
	/** Primary name attribute */
	PrimaryNameAttribute?: string;
	DefaultOnCreateActions?: ReactDefaultOnCreateAction[];
}

export interface ReactDefaultOnCreateAction {
	ConfigurationIdentifierMetadata: ReactConfigurationIdentifierMetadata[];
}

export interface ReactConfigurationIdentifierMetadata {
	ConfigurationIdentifier: string;
	FieldLogicalName: string;
	NavigationPropertyName: string;
}

/**
 * Re-export from Step.ts for convenience.
 */
export type { ReactFormStep } from "./Step";
