/**
 * Form configuration types.
 * These types mirror the C# ReactFormConfiguration classes generated by ReactFormBuilderService.
 */

export type {
	ReactFormConfiguration,
	ReactProgramConfiguration,
	ReactFundingOpportunityConfiguration,
	ReactFundingOpportunitySettings,
	ReactApplicationTableConfiguration,
	ReactForm,
	ReactFormSettings,
	ReactTableMetadataEntry,
	ReactConfigurationIdentifierMetadata,
} from "./Form";

export type { ReactFormStep } from "./Step";

export type { ReactActionConfiguration, ActionProperties } from "./Action";

export type { FieldInputProperties, FileUploadProperties, TableEntryProperties, FreeFormTextProperties, QuickViewProperties } from "./Properties";

export type { ReactConditionConfiguration, ReactConditionExpression } from "./Condition";
